import ContentBlock from '../components/ContentBlock'
import SourceChip from '../components/SourceChip'

export default function Genomics() {
  return (
    <div style={{ maxWidth: '860px' }}>
      <h1
        style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: '1.25rem',
          fontWeight: 700,
          color: 'var(--color-text-primary)',
          margin: '0 0 0.25rem 0',
        }}
      >
        GENOMICS & VIROLOGY
      </h1>
      <p
        style={{
          fontFamily: "'IBM Plex Sans', sans-serif",
          fontSize: '0.8125rem',
          color: 'var(--color-text-muted)',
          margin: '0 0 1.5rem 0',
        }}
      >
        Authoritative genomic and virological data for researchers, public health professionals, and
        informed practitioners. All content verbatim from identified sources. Links to primary
        sequence repositories provided.
      </p>

      <ContentBlock
        title="Virus Identification"
        content='Identification of Andes virus was performed through genomic sequencing at NICD and virus-specific PCR at Geneva University Hospitals. The causative agent of the 2026 MV Hondius outbreak has been confirmed as Orthohantavirus andesense (Andes virus, ANDV) by the World Health Organization following testing at multiple reference laboratories. WHO confirmed the Andes virus as causative agent on May 6, 2026, and published Disease Outbreak News DON599 on May 4, 2026.'
        authorityName="WHO"
        documentTitle="WHO Disease Outbreak News 599"
        publicationDate="2026-05-04"
        sourceUrl="https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599"
        license="CC BY-NC-SA 3.0 IGO"
      />

      <ContentBlock
        title="Strain Designation"
        content="The complete genome sequence of the 2026 outbreak strain has been designated: ANDV/Switzerland/Hu-3337/2026. The sequence was generated by the Swiss National Reference Center for Emerging Viral Infections in collaboration with Geneva University Hospitals and the University of Zurich. The complete genome was deposited on Virological.org on May 8, 2026 — the same day CDC issued HAN 528."
        authorityName="Virological.org"
        documentTitle="Complete sequence of Orthohantavirus andesense virus, Swiss resident 2026"
        publicationDate="2026-05-08"
        sourceUrl="https://virological.org/t/complete-sequence-of-orthohantavirus-andesense-virus-swiss-resident-2026/1023"
        license="CC BY 4.0"
      />

      {/* Sequence Repository Links */}
      <div
        style={{
          backgroundColor: 'var(--color-bg-secondary)',
          border: '1px solid var(--color-border)',
          borderRadius: '6px',
          padding: '1.25rem 1.5rem',
          marginBottom: '1rem',
        }}
      >
        <h2
          style={{
            fontFamily: "'IBM Plex Mono', monospace",
            fontSize: '0.875rem',
            fontWeight: 600,
            color: 'var(--color-text-primary)',
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
            margin: '0 0 0.75rem 0',
          }}
        >
          Sequence Repository Links
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem' }}>
          {[
            {
              label: 'Complete genome sequence — ANDV/Switzerland/Hu-3337/2026',
              url: 'https://virological.org/t/complete-sequence-of-orthohantavirus-andesense-virus-swiss-resident-2026/1023',
              authority: 'Virological.org',
              date: '2026-05-08',
            },
            {
              label: 'Pathoplexus multi-sequence analysis (5 patients) — cruise ship cluster',
              url: 'https://virological.org/t/preliminary-analysis-of-orthohantavirus-andesense-virus-sequences-from-a-cruise-ship-related-cluster-may-2026/1029',
              authority: 'Virological.org',
              date: '2026-05-09',
            },
            {
              label: 'Nextstrain — ANDV outbreak phylogenetic analysis (verify URL)',
              url: 'https://nextstrain.org',
              authority: 'Nextstrain',
              date: '2026-05-08',
            },
          ].map((link) => (
            <div
              key={link.url}
              style={{
                display: 'flex',
                alignItems: 'flex-start',
                gap: '0.75rem',
                padding: '0.625rem 0.75rem',
                backgroundColor: 'var(--color-bg-tertiary)',
                border: '1px solid var(--color-border)',
                borderRadius: '4px',
              }}
            >
              <div style={{ flex: 1 }}>
                <a
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    fontFamily: "'IBM Plex Sans', sans-serif",
                    fontSize: '0.875rem',
                    color: 'var(--color-accent-blue)',
                    textDecoration: 'none',
                    display: 'block',
                    marginBottom: '0.375rem',
                  }}
                >
                  {link.label} ↗
                </a>
                <SourceChip
                  authority={link.authority}
                  documentTitle={link.label}
                  date={link.date}
                  url={link.url}
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      <ContentBlock
        title="Laboratory Network"
        content="The following reference laboratories have contributed to the genomic identification and characterization of the 2026 Andes virus outbreak (WHO DON599):\n\n• National Institute for Communicable Diseases (NICD), South Africa — initial genomic sequencing\n• Geneva University Hospitals / University of Zurich, Switzerland — virus-specific PCR confirmation and full genome sequencing\n• Institut Pasteur de Dakar, Senegal — reference laboratory support\n• UK Health Security Agency (UKHSA), United Kingdom — reference laboratory support\n• National Institute for Public Health and the Environment (RIVM), Netherlands — reference laboratory support\n• Instituto Nacional de Enfermedades Virales Humanas (INEVH), Argentina — hantavirus reference laboratory"
        authorityName="WHO"
        documentTitle="WHO Disease Outbreak News 599"
        publicationDate="2026-05-04"
        sourceUrl="https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599"
        license="CC BY-NC-SA 3.0 IGO"
      />

      <ContentBlock
        title="Phylogenetic Summary"
        content={`The following expert statement is reproduced from the Science Media Centre expert reaction to the cruise ship hantavirus outbreak, attributed to Professor Piet Maes (Hantavirus Society / Plotkin Institute, University of Brussels):\n\n"The available phylogenetic and sequence data suggest that the Swiss patient isolate represents a relatively typical naturally circulating ANDV lineage originating from the established rodent reservoir in Chile/Argentina, rather than a highly divergent or newly emerged variant."\n\nAdditionally, from the Pathoplexus multi-sequence analysis published on Virological.org (May 9, 2026): "Sequences are all very similar to each other, suggesting a single zoonotic spill."\n\nThese findings indicate that the outbreak likely originated from a single index exposure event at or near the ship's departure point in Patagonia (Ushuaia, Argentina), with subsequent person-to-person transmission in confined shipboard conditions.`}
        authorityName="SMC"
        documentTitle="Expert reaction to cases of hantavirus on a cruise ship"
        publicationDate="2026-05-06"
        sourceUrl="https://www.sciencemediacentre.org/expert-reaction-to-cases-of-hantavirus-on-cruise-ship/"
      />

      <ContentBlock
        title="Genomic Segments (S, M, L)"
        content={`Andes virus, like all hantaviruses, has a trisegmented negative-sense single-stranded RNA genome comprising three segments:\n\n• S segment (Small): Encodes the nucleocapsid (N) protein. The N protein is the primary target for serological diagnostics (IgM/IgG ELISA).\n\n• M segment (Medium): Encodes the glycoprotein precursor (GPC), which is cleaved into Gn and Gc surface glycoproteins. These surface proteins mediate viral entry and are the primary targets for neutralizing antibodies.\n\n• L segment (Large): Encodes the RNA-dependent RNA polymerase (RdRp).\n\nFrom the Science Media Centre expert statement (Prof. Piet Maes): "Across all three genomic segments (S, M, and L), the virus clusters consistently with known South American Andes virus strains." This tri-segment phylogenetic consistency further supports a single, established reservoir origin rather than recombination or reassortment events.`}
        authorityName="SMC"
        documentTitle="Expert reaction to cases of hantavirus on a cruise ship"
        publicationDate="2026-05-06"
        sourceUrl="https://www.sciencemediacentre.org/expert-reaction-to-cases-of-hantavirus-on-cruise-ship/"
      />

      {/* Origin Investigation — prominently labeled unconfirmed */}
      <div
        style={{
          backgroundColor: 'var(--color-bg-secondary)',
          border: '1px solid var(--color-border)',
          borderLeft: '3px solid var(--color-accent-yellow)',
          borderRadius: '6px',
          padding: '1.25rem 1.5rem',
          marginBottom: '1rem',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            marginBottom: '0.75rem',
          }}
        >
          <h2
            style={{
              fontFamily: "'IBM Plex Mono', monospace",
              fontSize: '0.875rem',
              fontWeight: 600,
              color: 'var(--color-text-primary)',
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
              margin: 0,
            }}
          >
            Origin Investigation
          </h2>
          <span
            style={{
              padding: '0.125rem 0.5rem',
              backgroundColor: 'rgba(227, 179, 65, 0.15)',
              border: '1px solid var(--color-accent-yellow)',
              borderRadius: '3px',
              fontFamily: "'IBM Plex Mono', monospace",
              fontSize: '0.625rem',
              fontWeight: 700,
              color: 'var(--color-accent-yellow)',
              letterSpacing: '0.08em',
            }}
          >
            UNDER INVESTIGATION — UNCONFIRMED
          </span>
        </div>
        <p
          style={{
            fontFamily: "'IBM Plex Sans', sans-serif",
            fontSize: '0.9375rem',
            color: 'var(--color-text-secondary)',
            lineHeight: 1.7,
            margin: '0 0 0.75rem 0',
          }}
        >
          Media reports (Al Jazeera, Time Magazine) have speculated about possible exposure sites
          near Ushuaia, Argentina, including a landfill site and bird-watching excursions during the
          voyage. These reports are based on epidemiological speculation and have not been confirmed
          by authoritative sources.
        </p>
        <p
          style={{
            fontFamily: "'IBM Plex Sans', sans-serif",
            fontSize: '0.875rem',
            color: 'var(--color-text-muted)',
            lineHeight: 1.6,
            margin: '0 0 0.75rem 0',
            fontStyle: 'italic',
          }}
        >
          Important: As of May 12, 2026, the World Health Organization and the U.S. Centers for
          Disease Control and Prevention have not confirmed the specific origin event or exposure
          site for the index case. Investigations are ongoing.
        </p>
        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
          <span
            style={{
              fontFamily: "'IBM Plex Mono', monospace",
              fontSize: '0.6875rem',
              color: 'var(--color-text-muted)',
            }}
          >
            SOURCE:
          </span>
          <a
            href="https://www.aljazeera.com/news/2026/5/11/hantavirus-what-to-know"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontFamily: "'IBM Plex Mono', monospace",
              fontSize: '0.6875rem',
              color: 'var(--color-accent-blue)',
            }}
          >
            Al Jazeera (May 11, 2026) ↗
          </a>
          <a
            href="https://time.com/hantavirus-cruise-ship-outbreak-2026/"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontFamily: "'IBM Plex Mono', monospace",
              fontSize: '0.6875rem',
              color: 'var(--color-accent-blue)',
            }}
          >
            Time Magazine ↗
          </a>
        </div>
      </div>

      <ContentBlock
        title="Surveillance Context"
        content="Andes virus is endemic to the Patagonian region of Chile and Argentina, where the long-tailed pygmy rice rat (Oligoryzomys longicaudatus) serves as the primary reservoir host. The 2026 MV Hondius outbreak occurred following an Antarctic voyage departing Ushuaia — within the endemic range of ANDV in Argentine Patagonia.\n\nPre-outbreak surveillance context: Argentina's health ministry reported 101 hantavirus infections from June 2025 through early 2026 — roughly double the case count from the same period the prior year (source: Time Magazine / Associated Press). This elevated background incidence in the endemic region may reflect increased rodent activity, which has implications for zoonotic spillover risk.\n\nPAHO notes that endemic ANDV transmission in Chile and Argentina represents an ongoing public health challenge, with periodic cluster outbreaks and sporadic cases reported annually. The 2026 outbreak is the first documented mass-exposure event aboard a vessel originating from the endemic range."
        authorityName="PAHO"
        documentTitle="Hantavirus — Surveillance Context"
        publicationDate="2026"
        sourceUrl="https://www.paho.org/en/topics/hantavirus"
        license="CC BY-NC-SA 3.0 IGO"
      />

      <div
        style={{
          marginTop: '1.5rem',
          padding: '0.75rem 1rem',
          borderTop: '1px solid var(--color-border)',
          fontFamily: "'IBM Plex Sans', sans-serif",
          fontSize: '0.8125rem',
          color: 'var(--color-text-muted)',
        }}
      >
        All content on this page is reproduced from authoritative public health and scientific
        sources. View the full{' '}
        <a href="/sources" style={{ color: 'var(--color-accent-blue)', textDecoration: 'none' }}>
          Sources Registry →
        </a>
      </div>
    </div>
  )
}
